### ISSUE TITLE
connection lost

### ISSUE THREAD

**Issue by kevvie** [gruijter/com.gruijter.plugwise2py#4]
after the update the connection between homey and the pw2py server is lost and cannot be made again.

**Comment by gruijter** [comment]
Is pw2py on the latest version? See sevenWatts git for instructions howto:

https://github.com/SevenW/Plugwise-2-py

And also check if you are running the latest version of MQTT on your server :)

**Comment by kevvie** [comment]
I keep getting this error even after updating my MQTT server and both restarting my homey and my pi.
The app also keeps crashing.

![knipsel](https://user-images.githubusercontent.com/8775681/32837349-7dd31d58-ca0d-11e7-9088-69adcf581706.PNG)

**Comment by gruijter** [comment]
Hallo Kevvie,

Jammer dat het niet lekker loopt. Ik heb de migratie zo goed als het kon bij mijzelf getest. Maar misschien zitten er nog hele oude settings in je Homey (tenzij je de app het afgelopen half jaar opnieuw hebt geinstalleerd). Als het niet lukt kun je 2 dingen doen:

  *   Terug naar de oude versie (maar ik weet niet hoe lang Athom die nog laat werken op de oude SDK)
  *   De app verwijderen en opnieuw installeren. Je bent dan wel alle historie kwijt ☹

Bij mij werkt de versie 2.0.0 al ruim een week zonder problemen 😊

Laat je even weten hoe je vaart?

Thx!
Robin
Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: kevvie <notifications@github.com>
Verzonden: Wednesday, November 15, 2017 2:03:15 PM
Aan: gruijter/com.gruijter.plugwise2py
CC: gruijter; Comment
Onderwerp: Re: [gruijter/com.gruijter.plugwise2py] connection lost (#4)


I keep getting this error even after updating my MQTT server and both restarting my homey and my pi.
The app also keeps crashing.

[knipsel]<https://user-images.githubusercontent.com/8775681/32837349-7dd31d58-ca0d-11e7-9088-69adcf581706.PNG>
