### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by JPe2** [gruijter/com.gruijter.plugwise2py#5]
Haven't used it for a while, recently re-installed the Raspberry-pi completely after some crashes. On the Pi, it runs for several days stand-alone. Then started up your app on Homey and after a couple of hours, the app crashes again. The unique log ID is: 60ec4588-5c71-4b7d-a718-c788471f02e0
In stand-alone, the devices can be switched on and off, after connecting to Homey, no devices can be switched anymore and the Raspberry-pi needs to be rebooted. Is there something wrong with my installation or is there a problem in the Plugwise2py app?

**Comment by JPe2** [comment]
In the logfile:  pw-logger.log there sometimes (several times a day) the next line is printed:
_2018-01-30 14:03:50,068 - pw-logger - ERROR - protocol error [2]:'expected command ack from stick. received message with seqnr 5310 - this may be a duplicate message'_
can this be a reason for the crash?

**Comment by JPe2** [comment]
The log has been sent to the developer.
The unique log ID is: b3d0e753-98b5-4df3-909c-42b2b4da1bbe
![image](https://user-images.githubusercontent.com/3833862/36031260-6dd81864-0daa-11e8-975f-582efc068dde.png)

**Comment by gruijter** [comment]
Probably fixed by updating Homey firmware to 1.5.6
