### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Japio78** [gruijter/com.gruijter.plugwise2py#6]
Hallo het lukt mij niet, om in te loggen met plugwise@py, steeds weer timeout.
de confrigratie en besturing geen probleem mee, werkt prefect
wat doe ik eventueel fout

gr,
Jaap

**Comment by gruijter** [comment]
geen idee. Heb je al geprobeerd de app volledig te de-installeren, en weer opnieuw te installeren?
En kun je svp de debug logs hier posten?
