### ISSUE TITLE
2.0 compatible

### ISSUE THREAD

**Issue by cesarenl** [gruijter/com.gruijter.plugwise2py#7]
Is Plugwise2py compatible with Homey 2.0?

**Comment by gruijter** [comment]
IT should be, but maybe the app settings page doesn't show up properly. I havent tried yet. But Just install the app and see if the settings page comes up correctly😏

**Comment by cesarenl** [comment]
I haven't upgraded to 2.0 yet, I'm very dependent on this app, since I have about 12 circle modules that I use for monitoring and switching. Hence the question before upgrading ;)

**Comment by gruijter** [comment]
I could try Tomorrow if you want to be sure

**Comment by cesarenl** [comment]
Yes please! I'll patiently await your feedback!

**Comment by gruijter** [comment]
I just did some testing. If you migrate your Homey to V2 the app settings, devices and flows are kept, so it should all just work. If you do a new install under V2, the app settings page is not displayed correctly. This makes it difficult to save the mqtt settings. But I managed to do that from the app settings simulator tool under developer.athom.com :)

So you should be fine migrating to V2 🤗

I will update the plugwise2py app in a few weeks making the settings page look nice again.

**Comment by gruijter** [comment]
I updated the app to v2.0.6 to be optimized for Homey V2 settings page on a mobile device. It will be released in the appstore somewhere next week.
